/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import com.sun.glass.events.KeyEvent;
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Event;
import java.awt.Font;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.awt.event.WindowStateListener;
import java.util.ArrayList;
import java.util.List;
import javafx.scene.layout.Border;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.plaf.basic.BasicSplitPaneDivider;
import javax.swing.plaf.basic.BasicSplitPaneUI;

/**
 *
 * @author toze
 */
public class KeyQuest extends javax.swing.JFrame {

    /**
     * Creates new form KeyQuest
     */
    public KeyQuest() {
        initLang("fr-FR");
        initComponents();
        initAnotherComponents();
        caracteristicsJFrame();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInicial = new javax.swing.JPanel();
        jSplitPaneInicial = new javax.swing.JSplitPane();
        jPanelCima = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanelBaixo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusableWindowState(false);
        setMinimumSize(new java.awt.Dimension(700, 500));

        jPanelInicial.setBackground(new java.awt.Color(25, 25, 25));
        jPanelInicial.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(222, 222, 222)));
        jPanelInicial.setForeground(new java.awt.Color(224, 19, 19));
        jPanelInicial.setMinimumSize(new java.awt.Dimension(700, 400));
        jPanelInicial.setName(""); // NOI18N
        jPanelInicial.setPreferredSize(new java.awt.Dimension(700, 400));

        jSplitPaneInicial.setBackground(new java.awt.Color(1, 1, 1));
        jSplitPaneInicial.setDividerLocation(400);
        jSplitPaneInicial.setDividerSize(20);
        jSplitPaneInicial.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPaneInicial.setResizeWeight(0.5);
        jSplitPaneInicial.setAutoscrolls(true);
        jSplitPaneInicial.setMaximumSize(new java.awt.Dimension(21473434, 21473434));
        jSplitPaneInicial.setMinimumSize(new java.awt.Dimension(0, 0));
        jSplitPaneInicial.setName(""); // NOI18N
        jSplitPaneInicial.setOneTouchExpandable(true);
        jSplitPaneInicial.setPreferredSize(new java.awt.Dimension(800, 700));

        jPanelCima.setBackground(new java.awt.Color(158, 163, 199));
        jPanelCima.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanelCima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCimaMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("jButton1");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(281, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCimaLayout = new javax.swing.GroupLayout(jPanelCima);
        jPanelCima.setLayout(jPanelCimaLayout);
        jPanelCimaLayout.setHorizontalGroup(
            jPanelCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCimaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(639, Short.MAX_VALUE))
        );
        jPanelCimaLayout.setVerticalGroup(
            jPanelCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCimaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jSplitPaneInicial.setLeftComponent(jPanelCima);

        jPanelBaixo.setBackground(new java.awt.Color(40, 40, 40));
        jPanelBaixo.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanelBaixo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBaixoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 252, Short.MAX_VALUE)
        );

        jButton2.setText("Iniciar");
        jButton2.setToolTipText("");

        javax.swing.GroupLayout jPanelBaixoLayout = new javax.swing.GroupLayout(jPanelBaixo);
        jPanelBaixo.setLayout(jPanelBaixoLayout);
        jPanelBaixoLayout.setHorizontalGroup(
            jPanelBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaixoLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addGap(42, 42, 42)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanelBaixoLayout.setVerticalGroup(
            jPanelBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaixoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton2.setText(lingua.translate("Iniciar"));

        jSplitPaneInicial.setRightComponent(jPanelBaixo);

        javax.swing.GroupLayout jPanelInicialLayout = new javax.swing.GroupLayout(jPanelInicial);
        jPanelInicial.setLayout(jPanelInicialLayout);
        jPanelInicialLayout.setHorizontalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
        );
        jPanelInicialLayout.setVerticalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelBaixoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBaixoMouseClicked
        Component[] componentes = null;
        if (evt.getClickCount() == 2){
            componentes = jPanelCima.getComponents();
            jPanelCima.removeAll();
            jSplitPaneInicial.setDividerLocation(1);
        }
        if (componentes != null) {
            int i = 0;
            while (i < componentes.length) {
                jPanelCima.add(componentes[i]);
                i++;
            }
        }
    }//GEN-LAST:event_jPanelBaixoMouseClicked

    private void jPanelCimaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCimaMouseClicked
        Component[] componentes = null;
        if (evt.getClickCount() == 2){
            componentes = jPanelBaixo.getComponents();
            jPanelBaixo.removeAll();
            jSplitPaneInicial.setDividerLocation(jSplitPaneInicial.getWidth());         
        }
        if (componentes != null) {
            int i = 0;
            while (i < componentes.length) {
                jPanelBaixo.add(componentes[i]);
                i++;
            }
        }
        
    }//GEN-LAST:event_jPanelCimaMouseClicked

    public final void caracteristicsJFrame(){
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        
        //Listener nas abas do splitPaner
        jPanelBaixo.addComponentListener(new ComponentListener(){
            @Override
            public void componentResized(ComponentEvent e) {
                int i = 0;
                while (i < elementosBaixo.size()) {
                    elementosBaixo.get(i).putBounds(jPanelBaixo.getBounds().getSize().getWidth(), jPanelBaixo.getBounds().getSize().getHeight());
                    i++;
                }
            }
            @Override
            public void componentMoved(ComponentEvent e) {}
            @Override
            public void componentShown(ComponentEvent e) {}
            @Override
            public void componentHidden(ComponentEvent e) {}
        });
        jPanelCima.addComponentListener(new ComponentListener(){
            @Override
            public void componentResized(ComponentEvent e) {
                int i = 0;
                while (i < elementosCima.size()) {
                    elementosCima.get(i).putBounds(jPanelCima.getBounds().getSize().getWidth(), jPanelCima.getBounds().getSize().getHeight());
                    i++;
                }
            }
            @Override
            public void componentMoved(ComponentEvent e) {}
            @Override
            public void componentShown(ComponentEvent e) {}
            @Override
            public void componentHidden(ComponentEvent e) {}
        });
        
        // para qualquer necessidade windows state listener
        
        this.addWindowStateListener((WindowEvent e) -> {
           
        });
        
        // carcateristica de redimensionamento dos elementos dos painéis do SplitPane
        Component[] componentes = jPanelBaixo.getComponents();
        jPanelBaixo.removeAll();
        double factorX;
        double factorY;
        elementosBaixo = new ArrayList<>();
        if (componentes != null) {
            int i = 0;
            while (i < componentes.length) {
                jPanelBaixo.add(componentes[i]);
                factorX = jPanelBaixo.getBounds().getSize().getWidth();
                System.out.println(factorX);
                factorY = jPanelBaixo.getBounds().getSize().getHeight();
                elementosBaixo.add(new Element(componentes[i],factorX,factorY,true));
                i++;
            }
        }
        elementosCima = new ArrayList<>();
        componentes = jPanelCima.getComponents();
        jPanelCima.removeAll();
        if (componentes != null) {
            int i = 0;
            while (i < componentes.length) {
                jPanelCima.add(componentes[i]);
                factorX = jPanelCima.getBounds().getSize().getWidth();
                factorY = jPanelCima.getBounds().getSize().getHeight();
                elementosCima.add(new Element(componentes[i],factorX,factorY,false));
                i++;
            }
        }
        
        
        // Comportamento do duplo clique no separador  
        BasicSplitPaneUI ui = (BasicSplitPaneUI)jSplitPaneInicial.getUI();
        BasicSplitPaneDivider divisor = ui.getDivider();
        divisor.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2){
                     jSplitPaneInicial.setDividerLocation(0.4);
                }
            }
        });
        
        // Cursor Mão no separador do SplitPanel 
        divisor.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }
    
    public final void initAnotherComponents(){
        Menu menu = new Menu();
        JMenu menuFicheiro = new JMenu();
        JMenu jMenuEditar = new JMenu();
        menuFicheiro.setText(lingua.translate("Ficheiro"));
        menuFicheiro.setMnemonic(lingua.translate("Ficheiro").charAt(0));
        menuFicheiro.setCursor(new Cursor(Cursor.HAND_CURSOR));
        JMenuItem itemSair = new JMenuItem();
        itemSair.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, Event.ALT_MASK));
        //itemSair.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, Event.ALT_MASK | Event.CTRL_MASK));
        itemSair.setText(lingua.translate("Sair"));
        itemSair.setCursor(new Cursor(Cursor.HAND_CURSOR));
        itemSair.addActionListener((ActionEvent e) -> {
            sair(e);
        });
        menuFicheiro.add(itemSair);
        menu.add(menuFicheiro);
        jMenuEditar.setText(lingua.translate("Editar"));
        jMenuEditar.setMnemonic('E');
        jMenuEditar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        menu.add(jMenuEditar);
        this.setJMenuBar(menu);
        
        
    }
    
    public final void initLang(String string){
        lingua = new Langs.Locale();
        lingua.setLocale(string);
    }
    
    public void sair(ActionEvent e) {
        this.dispose();
        System.exit(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KeyQuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KeyQuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KeyQuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KeyQuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KeyQuest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton2;
    javax.swing.JButton jButton3;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanelBaixo;
    javax.swing.JPanel jPanelCima;
    javax.swing.JPanel jPanelInicial;
    javax.swing.JSplitPane jSplitPaneInicial;
    // End of variables declaration//GEN-END:variables
    private List<Element> elementosBaixo;
    private List<Element> elementosCima;
    private Langs.Locale lingua;
}
