/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import Clavis.Function;
import Clavis.TypeOfMaterial;
import TimeDate.Date;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Event;
import java.awt.Font;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.event.ActionEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowStateListener;
import java.util.prefs.Preferences;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.KeyStroke;
import javax.swing.plaf.basic.BasicSplitPaneDivider;
import javax.swing.plaf.basic.BasicSplitPaneUI;

/**
 *
 * @author António Santos
 */
public class KeyQuest extends javax.swing.JFrame {

    private static final long serialVersionUID =1L;
    /**
     * Creates new form KeyQuest
     */
    public KeyQuest() {
        initComponents();
        initAnotherComponents();
        caracteristicsJFrame();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelInicial = new javax.swing.JPanel();
        jSplitPaneInicial = new javax.swing.JSplitPane();
        jPanelBaixo = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanelCima = new javax.swing.JPanel();
        jScrollPaneMaterial = new javax.swing.JScrollPane();
        jTabbedPaneMaterial = new javax.swing.JTabbedPane();
        jScrollPaneRequisicoes = new javax.swing.JScrollPane();
        jLabelTitulorequisicoes = new javax.swing.JLabel();
        jLabelTituloOcupacoes = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestão de Recursos");
        setFocusableWindowState(false);
        setMinimumSize(new java.awt.Dimension(700, 400));

        jPanelInicial.setBackground(new java.awt.Color(25, 25, 25));
        jPanelInicial.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(254, 254, 254)));
        jPanelInicial.setForeground(new java.awt.Color(224, 19, 19));
        jPanelInicial.setMinimumSize(new java.awt.Dimension(700, 400));
        jPanelInicial.setName(""); // NOI18N
        jPanelInicial.setPreferredSize(new java.awt.Dimension(1000, 600));

        jSplitPaneInicial.setBackground(new java.awt.Color(1, 1, 1));
        jSplitPaneInicial.setDividerLocation(400);
        jSplitPaneInicial.setDividerSize(20);
        jSplitPaneInicial.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPaneInicial.setResizeWeight(0.5);
        jSplitPaneInicial.setAutoscrolls(true);
        jSplitPaneInicial.setMaximumSize(new java.awt.Dimension(21473434, 21473434));
        jSplitPaneInicial.setMinimumSize(new java.awt.Dimension(0, 0));
        jSplitPaneInicial.setName(""); // NOI18N
        jSplitPaneInicial.setOneTouchExpandable(true);
        jSplitPaneInicial.setPreferredSize(new java.awt.Dimension(1000, 600));

        jPanelBaixo.setBackground(new java.awt.Color(40, 40, 40));
        jPanelBaixo.setMinimumSize(new java.awt.Dimension(1, 1));
        jPanelBaixo.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanelBaixo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBaixoMouseClicked(evt);
            }
        });

        jButton2.setText("Iniciar");
        jButton2.setToolTipText("");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanelBaixoLayout = new javax.swing.GroupLayout(jPanelBaixo);
        jPanelBaixo.setLayout(jPanelBaixoLayout);
        jPanelBaixoLayout.setHorizontalGroup(
            jPanelBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBaixoLayout.createSequentialGroup()
                .addContainerGap(288, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBaixoLayout.setVerticalGroup(
            jPanelBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBaixoLayout.createSequentialGroup()
                .addGroup(jPanelBaixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBaixoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelBaixoLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setText(lingua.translate("Iniciar"));

        jSplitPaneInicial.setRightComponent(jPanelBaixo);

        jPanelCima.setBackground(new java.awt.Color(158, 163, 199));
        jPanelCima.setAutoscrolls(true);
        jPanelCima.setMinimumSize(new java.awt.Dimension(1, 1));
        jPanelCima.setName(""); // NOI18N
        jPanelCima.setPreferredSize(new java.awt.Dimension(300, 200));
        jPanelCima.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCimaMouseClicked(evt);
            }
        });

        jScrollPaneMaterial.setBackground(new java.awt.Color(97, 97, 97));
        jScrollPaneMaterial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPaneMaterial.setMinimumSize(new java.awt.Dimension(0, 0));
        jScrollPaneMaterial.setViewportView(jTabbedPaneMaterial);

        jScrollPaneRequisicoes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPaneRequisicoes.setInheritsPopupMenu(true);
        jScrollPaneRequisicoes.setMinimumSize(new java.awt.Dimension(400, 400));

        jLabelTitulorequisicoes.setBackground(new java.awt.Color(50, 50, 50));
        jLabelTitulorequisicoes.setForeground(new java.awt.Color(254, 254, 254));
        jLabelTitulorequisicoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulorequisicoes.setLabelFor(jLabelTitulorequisicoes);
        jLabelTitulorequisicoes.setText("Lista de requisições");
        jLabelTitulorequisicoes.setText(lingua.translate("Lista_de_requisições"));
        jLabelTitulorequisicoes.setAlignmentX(0.5F);
        jLabelTitulorequisicoes.setOpaque(true);
        jLabelTitulorequisicoes.setForeground(Color.WHITE);
        jLabelTitulorequisicoes.setFont(new Font("Cantarell",Font.BOLD,18));

        jLabelTituloOcupacoes.setBackground(new java.awt.Color(50, 50, 50));
        jLabelTituloOcupacoes.setForeground(new java.awt.Color(254, 254, 254));
        jLabelTituloOcupacoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloOcupacoes.setText("Detalhes / horários das salas");
        jLabelTituloOcupacoes.setText(lingua.translate("detalhes_salas"));
        jLabelTituloOcupacoes.setAlignmentX(0.5F);
        jLabelTituloOcupacoes.setOpaque(true);
        jLabelTituloOcupacoes.setForeground(Color.WHITE);
        jLabelTituloOcupacoes.setFont(new Font("Cantarell",Font.BOLD,18));

        jPanel2.setBackground(new java.awt.Color(187, 86, 46));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCimaLayout = new javax.swing.GroupLayout(jPanelCima);
        jPanelCima.setLayout(jPanelCimaLayout);
        jPanelCimaLayout.setHorizontalGroup(
            jPanelCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCimaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulorequisicoes, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                    .addComponent(jScrollPaneRequisicoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPaneMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelTituloOcupacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCimaLayout.setVerticalGroup(
            jPanelCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCimaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulorequisicoes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTituloOcupacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCimaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(jScrollPaneRequisicoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPaneMaterial.setOpaque(true);

        jSplitPaneInicial.setLeftComponent(jPanelCima);

        javax.swing.GroupLayout jPanelInicialLayout = new javax.swing.GroupLayout(jPanelInicial);
        jPanelInicial.setLayout(jPanelInicialLayout);
        jPanelInicialLayout.setHorizontalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
        );
        jPanelInicialLayout.setVerticalGroup(
            jPanelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPaneInicial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
        );

        jSplitPaneInicial.setResizeWeight(1.0);

        jToolBar1.setRollover(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 681, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelCimaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCimaMouseClicked
        if (evt.getClickCount() == 2) jSplitPaneInicial.setDividerLocation(jSplitPaneInicial.getWidth());
    }//GEN-LAST:event_jPanelCimaMouseClicked

    private void jPanelBaixoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBaixoMouseClicked
        if (evt.getClickCount() == 2)  jSplitPaneInicial.setDividerLocation(0);
    }//GEN-LAST:event_jPanelBaixoMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        lingua.setLocale("pt_PT");
        prefs.stop();
        prefs = new PersonalPrefs();
        prefs.start();
        this.dispose();
        prefs.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    public final void caracteristicsJFrame() {
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.addWindowStateListener(new WindowStateListener() {

            // conseguir tamanho do monitor... multi-monitor 
            GraphicsDevice gd = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
            int width = gd.getDisplayMode().getWidth();
            int height = gd.getDisplayMode().getHeight();

            // conseguir tamanho do monitor... simples
            /*
             Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
             double width = screenSize.getWidth();
             double height = screenSize.getHeight();
             */
            @Override
            public void windowStateChanged(WindowEvent e) {
                if (e.getOldState() == 6) {
                    int x = ((width / 2) - 500);
                    int y = ((height / 2) - 350);
                    setBounds(x, y, 1000, 700);
                }
            }
        });
        
        this.addWindowListener(new WindowAdapter(){
            @Override
            public void windowClosing(WindowEvent e)
            {
                prefs.stop();
            }
        });

        // Comportamento do duplo clique no separador  
        BasicSplitPaneUI ui = (BasicSplitPaneUI) jSplitPaneInicial.getUI();
        BasicSplitPaneDivider divisor = ui.getDivider();
        divisor.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                if (evt.getClickCount() == 2) {
                    jSplitPaneInicial.setDividerLocation(0.5);
                }
            }
        });
        // Cursor Mão no separador do SplitPanel 
        divisor.setCursor(new Cursor(Cursor.HAND_CURSOR));

        //jTableReq.getTableHeader().setPreferredSize(new Dimension(40,40));
    }

    public final void initAnotherComponents() {
        Menu menu = new Menu();
        JMenu menuFicheiro = new JMenu();
        JMenu jMenuEditar = new JMenu();
        menuFicheiro.setText(lingua.translate("Ficheiro"));
        menuFicheiro.setMnemonic(lingua.translate("Ficheiro").charAt(0));
        JMenuItem itemSair = new JMenuItem();
        itemSair.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, Event.ALT_MASK));
        itemSair.setText(lingua.translate("Sair"));
        itemSair.setCursor(new Cursor(Cursor.HAND_CURSOR));
        itemSair.addActionListener((ActionEvent e) -> {
            sair(e);
        });
        menuFicheiro.add(itemSair);
        menu.add(menuFicheiro);
        jMenuEditar.setText(lingua.translate("Editar"));
        jMenuEditar.setMnemonic('E');
        menu.add(jMenuEditar);
        this.setJMenuBar(menu);
        
        Function funcao = new Function("Professor", 2);
        TypeOfMaterial material = new TypeOfMaterial("Salas", 70);
        Date datainicio = new Date(24, 3, 2016);
        Date datafim = new Date(29, 4, 2016);
        urlcsv = "http://localhost:8080/horario_disciplinas.csv";
        HolidaysList lista = new HolidaysList(2016);
        lista.addCorpusChristi();
        //lista.addHoliday(25, 04);
        requisicoes = new RequestList("", urlcsv, material, funcao, datainicio, datafim, lista);
        
        /* Timer java.util
        java.util.Timer tim = new java.util.Timer();
        tim.schedule(new java.util.TimerTask(){
            @Override
            public void run() {
                JOptionPane.showMessageDialog(rootPane, "Ola mundo");
                System.out.println(new java.util.Date().getTime());
            }
        
        },1000*10);
        */
        
        
        /* javax.swing.timer
        Timer t = new Timer(10000, (ActionEvent e) -> {
            JOptionPane.showMessageDialog(rootPane, "Olass mundo");
        });
        t.start();
        t.setRepeats(true);
        */
        
        requisicoes.make();
        jScrollPaneRequisicoes.setViewportView(new TableRequest(requisicoes,lingua).getTable());
        btrequests = new ButtonListRequest(requisicoes,lingua);
       
        
        jTabbedPaneMaterial.add(btrequests.getScrollPane());
        jTabbedPaneMaterial.setTitleAt(0, lingua.translate(material.getTypeOfMaterialName()));
       
        
    }

    public void sair(ActionEvent e) {
        prefs.stop();
        this.dispose();
        System.exit(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KeyQuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KeyQuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KeyQuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KeyQuest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Preferences userPrefs = Preferences.userNodeForPackage(getClass());
                String lang = userPrefs.get("lingua", "pt_PT");
                lingua = new Langs.Locale();
                lingua.setLocale(lang);
                prefs = new PersonalPrefs();
                prefs.start();
                prefs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                prefs.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton2;
    javax.swing.JLabel jLabelTituloOcupacoes;
    javax.swing.JLabel jLabelTitulorequisicoes;
    javax.swing.JPanel jPanel1;
    javax.swing.JPanel jPanel2;
    javax.swing.JPanel jPanelBaixo;
    javax.swing.JPanel jPanelCima;
    javax.swing.JPanel jPanelInicial;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JScrollPane jScrollPaneMaterial;
    javax.swing.JScrollPane jScrollPaneRequisicoes;
    javax.swing.JSplitPane jSplitPaneInicial;
    javax.swing.JTabbedPane jTabbedPaneMaterial;
    javax.swing.JTable jTable1;
    javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
    
    private RequestList requisicoes;
    private String urlbd;
    private String urlcsv;
    private static PersonalPrefs prefs;
    protected static Langs.Locale lingua;
    private ButtonListRequest btrequests;

}
